"""Added new column to Special model

Revision ID: 6a2e26186415
Revises: 
Create Date: 2025-10-01 21:10:14.633306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2e26186415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
