"""empty message

Revision ID: ed685fbf42de
Revises: 6a2e26186415
Create Date: 2025-10-01 22:31:21.179931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed685fbf42de'
down_revision = '6a2e26186415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oPrice', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nPrice', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('special', schema=None) as batch_op:
        batch_op.drop_column('nPrice')
        batch_op.drop_column('oPrice')

    # ### end Alembic commands ###
